
/*
 * This file was generated by the SOM Compiler.
 * FileName: WPSAM.h.
 * Generated using:
 *     SOM Precompiler spc: 1.22
 *     SOM Emitter emith: 1.11
 */

/*
 * 
 * 
 * 
 *   Module Name: WPSam
 * 
 *   OS/2 Workplace Shell Access Manager
 * 
 */


#ifndef WPSAM_h
#define WPSAM_h


#include <som.h>

/*
 * Define the class name as an object type
 */
#ifndef WPSam
#define WPSam SOMAny
#endif
#include "wpfolder.h"

/*
 * Passthru lines: File: "C.h", "after"
 */


#define WPSam_MajorVersion 1
#define WPSam_MinorVersion 1

/*
 * External name shortening if required
 */
#ifdef SOM_USE_SHORT_EXTERNAL_NAMES
#define WPSamNewClass wpsamc
#pragma linkage(wpsamc, system)
#define WPSamClassData wpsamd
#define WPSamCClassData wpsamx
#endif /* SOM_USE_SHORT_EXTERNAL_NAMES */
/*--------------Migration------------*/
#define WPSam_classObj WPSamClassData.classObject
#define _WPSam WPSam_classObj

/*
 * New and Renew macros for WPSam
 */
#define _WPSamNew() (_somNew(WPSamClassData.classObject))
#define WPSamNew() \
	( WPSamClassData.classObject \
		? _WPSamNew() \
		: ( WPSamNewClass(WPSam_MajorVersion, WPSam_MinorVersion), _WPSamNew() ) )
#define WPSamRenew(buf) \
	( _somRenew(WPSamClassData.classObject, buf) )

/*
 * Override method: wpInitData
 */
#define WPSam_wpInitData(somSelf) \
	WPObject_wpInitData(somSelf)

/*
 * Override method: wpUnInitData
 */
#define WPSam_wpUnInitData(somSelf) \
	WPObject_wpUnInitData(somSelf)

/*
 * Override method: wpSetup
 */
#define WPSam_wpSetup(somSelf,pszSetupString) \
	WPObject_wpSetup(somSelf,pszSetupString)

/*
 * Override method: wpCopiedFromTemplate
 */
#define WPSam_wpCopiedFromTemplate(somSelf) \
	WPObject_wpCopiedFromTemplate(somSelf)

/*
 * Override method: wpSaveState
 */
#define WPSam_wpSaveState(somSelf) \
	WPObject_wpSaveState(somSelf)

/*
 * Override method: wpRestoreState
 */
#define WPSam_wpRestoreState(somSelf,ulReserved) \
	WPObject_wpRestoreState(somSelf,ulReserved)

/*
 * Override method: wpOpen
 */
#define WPSam_wpOpen(somSelf,hwndCnr,ulView,param) \
	WPObject_wpOpen(somSelf,hwndCnr,ulView,param)

/*
 * Override method: wpDelete
 */
#define WPSam_wpDelete(somSelf,fConfirmations) \
	WPObject_wpDelete(somSelf,fConfirmations)

/*
 * Override method: wpConfirmDelete
 */
#define WPSam_wpConfirmDelete(somSelf,fConfirmations) \
	WPObject_wpConfirmDelete(somSelf,fConfirmations)

/*
 * Override method: wpAddSettingsPages
 */
#define WPSam_wpAddSettingsPages(somSelf,hwndNotebook) \
	WPObject_wpAddSettingsPages(somSelf,hwndNotebook)

/*
 * Override method: wpModifyPopupMenu
 */
#define WPSam_wpModifyPopupMenu(somSelf,hwndMenu,hwndCnr,iPosition) \
	WPObject_wpModifyPopupMenu(somSelf,hwndMenu,hwndCnr,iPosition)

/*
 * Override method: wpMenuItemSelected
 */
#define WPSam_wpMenuItemSelected(somSelf,hwndFrame,ulMenuId) \
	WPObject_wpMenuItemSelected(somSelf,hwndFrame,ulMenuId)

/*
 * Override method: wpMenuItemHelpSelected
 */
#define WPSam_wpMenuItemHelpSelected(somSelf,MenuId) \
	WPObject_wpMenuItemHelpSelected(somSelf,MenuId)

/*
 * New Method: CheckPassword
 */
typedef BOOL    SOMLINK somTP_WPSam_CheckPassword(WPSam *somSelf);
#pragma linkage(somTP_WPSam_CheckPassword, system)
typedef somTP_WPSam_CheckPassword *somTD_WPSam_CheckPassword;
#define somMD_WPSam_CheckPassword "----"
#define WPSam_CheckPassword(somSelf) \
    (SOM_Resolve(somSelf, WPSam, CheckPassword) \
	(somSelf))
#define _CheckPassword WPSam_CheckPassword

/*
 * New Method: RefreshStyle
 */
typedef BOOL    SOMLINK somTP_WPSam_RefreshStyle(WPSam *somSelf);
#pragma linkage(somTP_WPSam_RefreshStyle, system)
typedef somTP_WPSam_RefreshStyle *somTD_WPSam_RefreshStyle;
#define somMD_WPSam_RefreshStyle "----"
#define WPSam_RefreshStyle(somSelf) \
    (SOM_Resolve(somSelf, WPSam, RefreshStyle) \
	(somSelf))
#define _RefreshStyle WPSam_RefreshStyle

/*
 * New Method: CommonSetup
 */
typedef BOOL    SOMLINK somTP_WPSam_CommonSetup(WPSam *somSelf);
#pragma linkage(somTP_WPSam_CommonSetup, system)
typedef somTP_WPSam_CommonSetup *somTD_WPSam_CommonSetup;
#define somMD_WPSam_CommonSetup "----"
#define WPSam_CommonSetup(somSelf) \
    (SOM_Resolve(somSelf, WPSam, CommonSetup) \
	(somSelf))
#define _CommonSetup WPSam_CommonSetup

/*
 * New Method: ProfilesCreated
 */
typedef BOOL    SOMLINK somTP_WPSam_ProfilesCreated(WPSam *somSelf);
#pragma linkage(somTP_WPSam_ProfilesCreated, system)
typedef somTP_WPSam_ProfilesCreated *somTD_WPSam_ProfilesCreated;
#define somMD_WPSam_ProfilesCreated "----"
#define WPSam_ProfilesCreated(somSelf) \
    (SOM_Resolve(somSelf, WPSam, ProfilesCreated) \
	(somSelf))
#define _ProfilesCreated WPSam_ProfilesCreated

/*
 * New Method: MyHistory
 */
typedef BOOL    SOMLINK somTP_WPSam_MyHistory(WPSam *somSelf,
		ULONG ulIDS);
#pragma linkage(somTP_WPSam_MyHistory, system)
typedef somTP_WPSam_MyHistory *somTD_WPSam_MyHistory;
#define somMD_WPSam_MyHistory "----"
#define WPSam_MyHistory(somSelf,ulIDS) \
    (SOM_Resolve(somSelf, WPSam, MyHistory) \
	(somSelf,ulIDS))
#define _MyHistory WPSam_MyHistory

/*
 * Declare the class creation procedure
 */
SOMEXTERN SOMAny * SOMLINK WPSamNewClass(integer4 scemajorVersion,
		integer4 sceminorVersion);
#pragma linkage(WPSamNewClass, system)

/*
 * Declare the class data structure
 */
SOMEXTERN struct WPSamClassDataStructure {
	SOMAny *classObject;
	somMToken CheckPassword;
	somMToken RefreshStyle;
	somMToken CommonSetup;
	somMToken ProfilesCreated;
	somMToken MyHistory;
} WPSamClassData;

/*
 * Declare the C specific class data structure
 */
SOMEXTERN struct WPSamCClassDataStructure {
	somMethodTab *parentMtab;
	somDToken instanceDataToken;
} WPSamCClassData;

#endif       /* WPSAM_h */

/*
 * This file was generated by the SOM Compiler.
 * FileName: WPSAM.h.
 * Generated using:
 *     SOM Precompiler spc: 1.22
 *     SOM Emitter emith: 1.11
 */

#ifndef WPSAM_mh
#define WPSAM_mh


/*
 * Define the class name as an object type
 */
#ifndef M_WPSam
#define M_WPSam SOMAny
#endif

#define M_WPSam_MajorVersion 1
#define M_WPSam_MinorVersion 1

/*
 * External name shortening if required
 */
#ifdef SOM_USE_SHORT_EXTERNAL_NAMES
#define M_WPSamNewClass wpsamc
#pragma linkage(wpsamc, system)
#define M_WPSamClassData wpsamd
#define M_WPSamCClassData wpsamx
#endif /* SOM_USE_SHORT_EXTERNAL_NAMES */
/*--------------Migration------------*/
#define M_WPSam_classObj M_WPSamClassData.classObject
#define _M_WPSam M_WPSam_classObj

/*
 * New and Renew macros for M_WPSam
 */
#define _M_WPSamNew() (_somNew(M_WPSamClassData.classObject))
#define M_WPSamNew() \
	( M_WPSamClassData.classObject \
		? _M_WPSamNew() \
		: ( M_WPSamNewClass(M_WPSam_MajorVersion, M_WPSam_MinorVersion), _M_WPSamNew() ) )
#define M_WPSamRenew(buf) \
	( _somRenew(M_WPSamClassData.classObject, buf) )

/*
 * Override method: wpclsInitData
 */
#define M_WPSam_wpclsInitData(somSelf) \
	M_WPObject_wpclsInitData(somSelf)

/*
 * Override method: wpclsUnInitData
 */
#define M_WPSam_wpclsUnInitData(somSelf) \
	M_WPObject_wpclsUnInitData(somSelf)

/*
 * Override method: wpclsQueryDefaultView
 */
#define M_WPSam_wpclsQueryDefaultView(somSelf) \
	M_WPObject_wpclsQueryDefaultView(somSelf)

/*
 * Override method: wpclsQueryIconData
 */
#define M_WPSam_wpclsQueryIconData(somSelf,pIconInfo) \
	M_WPObject_wpclsQueryIconData(somSelf,pIconInfo)

/*
 * Override method: wpclsQueryStyle
 */
#define M_WPSam_wpclsQueryStyle(somSelf) \
	M_WPObject_wpclsQueryStyle(somSelf)

/*
 * Override method: wpclsQueryTitle
 */
#define M_WPSam_wpclsQueryTitle(somSelf) \
	M_WPObject_wpclsQueryTitle(somSelf)

/*
 * New Method: clsQueryModuleHandle
 */
typedef HMODULE    SOMLINK somTP_M_WPSam_clsQueryModuleHandle(M_WPSam *somSelf);
#pragma linkage(somTP_M_WPSam_clsQueryModuleHandle, system)
typedef somTP_M_WPSam_clsQueryModuleHandle *somTD_M_WPSam_clsQueryModuleHandle;
#define somMD_M_WPSam_clsQueryModuleHandle "----"
#define M_WPSam_clsQueryModuleHandle(somSelf) \
    (SOM_Resolve(somSelf, M_WPSam, clsQueryModuleHandle) \
	(somSelf))
#define _clsQueryModuleHandle M_WPSam_clsQueryModuleHandle

/*
 * New Method: clsIsShareware
 */
typedef BOOL    SOMLINK somTP_M_WPSam_clsIsShareware(M_WPSam *somSelf);
#pragma linkage(somTP_M_WPSam_clsIsShareware, system)
typedef somTP_M_WPSam_clsIsShareware *somTD_M_WPSam_clsIsShareware;
#define somMD_M_WPSam_clsIsShareware "----"
#define M_WPSam_clsIsShareware(somSelf) \
    (SOM_Resolve(somSelf, M_WPSam, clsIsShareware) \
	(somSelf))
#define _clsIsShareware M_WPSam_clsIsShareware

/*
 * New Method: clsAbout
 */
typedef void    SOMLINK somTP_M_WPSam_clsAbout(M_WPSam *somSelf);
#pragma linkage(somTP_M_WPSam_clsAbout, system)
typedef somTP_M_WPSam_clsAbout *somTD_M_WPSam_clsAbout;
#define somMD_M_WPSam_clsAbout "----"
#define M_WPSam_clsAbout(somSelf) \
    (SOM_Resolve(somSelf, M_WPSam, clsAbout) \
	(somSelf))
#define _clsAbout M_WPSam_clsAbout

/*
 * New Method: clsQueryRegFile
 */
typedef PCHAR    SOMLINK somTP_M_WPSam_clsQueryRegFile(M_WPSam *somSelf);
#pragma linkage(somTP_M_WPSam_clsQueryRegFile, system)
typedef somTP_M_WPSam_clsQueryRegFile *somTD_M_WPSam_clsQueryRegFile;
#define somMD_M_WPSam_clsQueryRegFile "----"
#define M_WPSam_clsQueryRegFile(somSelf) \
    (SOM_Resolve(somSelf, M_WPSam, clsQueryRegFile) \
	(somSelf))
#define _clsQueryRegFile M_WPSam_clsQueryRegFile

/*
 * Declare the class creation procedure
 */
SOMEXTERN SOMAny * SOMLINK M_WPSamNewClass(integer4 scemajorVersion,
		integer4 sceminorVersion);
#pragma linkage(M_WPSamNewClass, system)

/*
 * Declare the class data structure
 */
SOMEXTERN struct M_WPSamClassDataStructure {
	SOMAny *classObject;
	somMToken clsQueryModuleHandle;
	somMToken clsIsShareware;
	somMToken clsQueryRegFile;
	somMToken clsAbout;
} M_WPSamClassData;

/*
 * Declare the C specific class data structure
 */
SOMEXTERN struct M_WPSamCClassDataStructure {
	somMethodTab *parentMtab;
	somDToken instanceDataToken;
} M_WPSamCClassData;

#endif       /* WPSAM_h */
