
# This file was generated by the SOM Compiler.
# FileName: WPSAM.psc.
# Generated using:
#     SOM Precompiler spc: 1.22
#     SOM Emitter emitpsc: 1.10

/*
 * 
 * 
 *   Module Name: WPSam
 * 
 *   OS/2 Workplace Shell Access Manager
 * 
 */


/*
 * Include the .sc file
 */
#include "WPSAM.sc"

class: WPSam;

