
# This file was generated by the SOM Compiler.
# FileName: WPSAMF.psc.
# Generated using:
#     SOM Precompiler spc: 1.22
#     SOM Emitter emitpsc: 1.10

/*
 * 
 * 
 *   Module Name: WPSamFolder
 * 
 *   OS/2 Workplace Shell Access Manager
 * 
 *   Container for userdefined desktops
 * 
 */


/*
 * Include the .sc file
 */
#include "WPSAMF.sc"

class: WPSamF;

