
/*
 * This file was generated by the SOM Compiler.
 * FileName: WPSAMF.h.
 * Generated using:
 *     SOM Precompiler spc: 1.22
 *     SOM Emitter emith: 1.11
 */

/*
 * 
 * 
 * 
 *   Module Name: WPSamFolder
 * 
 *   OS/2 Workplace Shell Access Manager
 * 
 *   Container for userdefined desktops
 * 
 */


#ifndef WPSAMF_h
#define WPSAMF_h


#include <som.h>

/*
 * Define the class name as an object type
 */
#ifndef WPSamF
#define WPSamF SOMAny
#endif
#include "wpdesk.h"

/*
 * Passthru lines: File: "C.h", "after"
 */


#define WPSamF_MajorVersion 1
#define WPSamF_MinorVersion 1

/*
 * External name shortening if required
 */
#ifdef SOM_USE_SHORT_EXTERNAL_NAMES
#define WPSamFNewClass WPSamFc
#pragma linkage(WPSamFc, system)
#define WPSamFClassData WPSamFd
#define WPSamFCClassData WPSamFx
#endif /* SOM_USE_SHORT_EXTERNAL_NAMES */
/*--------------Migration------------*/
#define WPSamF_classObj WPSamFClassData.classObject
#define _WPSamF WPSamF_classObj

/*
 * New and Renew macros for WPSamF
 */
#define _WPSamFNew() (_somNew(WPSamFClassData.classObject))
#define WPSamFNew() \
	( WPSamFClassData.classObject \
		? _WPSamFNew() \
		: ( WPSamFNewClass(WPSamF_MajorVersion, WPSamF_MinorVersion), _WPSamFNew() ) )
#define WPSamFRenew(buf) \
	( _somRenew(WPSamFClassData.classObject, buf) )

/*
 * Override method: wpInitData
 */
#define WPSamF_wpInitData(somSelf) \
	WPObject_wpInitData(somSelf)

/*
 * Override method: wpSaveState
 */
#define WPSamF_wpSaveState(somSelf) \
	WPObject_wpSaveState(somSelf)

/*
 * Override method: wpRestoreState
 */
#define WPSamF_wpRestoreState(somSelf,ulReserved) \
	WPObject_wpRestoreState(somSelf,ulReserved)

/*
 * Override method: wpAddSettingsPages
 */
#define WPSamF_wpAddSettingsPages(somSelf,hwndNotebook) \
	WPObject_wpAddSettingsPages(somSelf,hwndNotebook)

/*
 * Override method: wpFilterPopupMenu
 */
#define WPSamF_wpFilterPopupMenu(somSelf,ulFlags,hwndCnr,fMultiSelect) \
	WPObject_wpFilterPopupMenu(somSelf,ulFlags,hwndCnr,fMultiSelect)

/*
 * Override method: wpModifyPopupMenu
 */
#define WPSamF_wpModifyPopupMenu(somSelf,hwndMenu,hwndCnr,iPosition) \
	WPObject_wpModifyPopupMenu(somSelf,hwndMenu,hwndCnr,iPosition)

/*
 * Override method: wpMenuItemSelected
 */
#define WPSamF_wpMenuItemSelected(somSelf,hwndFrame,ulMenuId) \
	WPObject_wpMenuItemSelected(somSelf,hwndFrame,ulMenuId)

/*
 * Override method: wpMenuItemHelpSelected
 */
#define WPSamF_wpMenuItemHelpSelected(somSelf,MenuId) \
	WPObject_wpMenuItemHelpSelected(somSelf,MenuId)

/*
 * Override method: wpOpen
 */
#define WPSamF_wpOpen(somSelf,hwndCnr,ulView,param) \
	WPObject_wpOpen(somSelf,hwndCnr,ulView,param)

/*
 * New Method: RootDesktop
 */
typedef BOOL    SOMLINK somTP_WPSamF_RootDesktop(WPSamF *somSelf);
#pragma linkage(somTP_WPSamF_RootDesktop, system)
typedef somTP_WPSamF_RootDesktop *somTD_WPSamF_RootDesktop;
#define somMD_WPSamF_RootDesktop "----"
#define WPSamF_RootDesktop(somSelf) \
    (SOM_Resolve(somSelf, WPSamF, RootDesktop) \
	(somSelf))
#define _RootDesktop WPSamF_RootDesktop

/*
 * Declare the class creation procedure
 */
SOMEXTERN SOMAny * SOMLINK WPSamFNewClass(integer4 scemajorVersion,
		integer4 sceminorVersion);
#pragma linkage(WPSamFNewClass, system)

/*
 * Declare the class data structure
 */
SOMEXTERN struct WPSamFClassDataStructure {
	SOMAny *classObject;
	somMToken RootDesktop;
} WPSamFClassData;

/*
 * Declare the C specific class data structure
 */
SOMEXTERN struct WPSamFCClassDataStructure {
	somMethodTab *parentMtab;
	somDToken instanceDataToken;
} WPSamFCClassData;

#endif       /* WPSAMF_h */

/*
 * This file was generated by the SOM Compiler.
 * FileName: WPSAMF.h.
 * Generated using:
 *     SOM Precompiler spc: 1.22
 *     SOM Emitter emith: 1.11
 */

#ifndef WPSAMF_mh
#define WPSAMF_mh


/*
 * Define the class name as an object type
 */
#ifndef M_WPSamF
#define M_WPSamF SOMAny
#endif

#define M_WPSamF_MajorVersion 1
#define M_WPSamF_MinorVersion 1

/*
 * External name shortening if required
 */
#ifdef SOM_USE_SHORT_EXTERNAL_NAMES
#define M_WPSamFNewClass WPSamFc
#pragma linkage(WPSamFc, system)
#define M_WPSamFClassData WPSamFd
#define M_WPSamFCClassData WPSamFx
#endif /* SOM_USE_SHORT_EXTERNAL_NAMES */
/*--------------Migration------------*/
#define M_WPSamF_classObj M_WPSamFClassData.classObject
#define _M_WPSamF M_WPSamF_classObj

/*
 * New and Renew macros for M_WPSamF
 */
#define _M_WPSamFNew() (_somNew(M_WPSamFClassData.classObject))
#define M_WPSamFNew() \
	( M_WPSamFClassData.classObject \
		? _M_WPSamFNew() \
		: ( M_WPSamFNewClass(M_WPSamF_MajorVersion, M_WPSamF_MinorVersion), _M_WPSamFNew() ) )
#define M_WPSamFRenew(buf) \
	( _somRenew(M_WPSamFClassData.classObject, buf) )

/*
 * Override method: wpclsInitData
 */
#define M_WPSamF_wpclsInitData(somSelf) \
	M_WPObject_wpclsInitData(somSelf)

/*
 * Override method: wpclsQueryTitle
 */
#define M_WPSamF_wpclsQueryTitle(somSelf) \
	M_WPObject_wpclsQueryTitle(somSelf)

/*
 * New Method: clsQueryModuleHandle
 */
typedef HMODULE    SOMLINK somTP_M_WPSamF_clsQueryModuleHandle(M_WPSamF *somSelf);
#pragma linkage(somTP_M_WPSamF_clsQueryModuleHandle, system)
typedef somTP_M_WPSamF_clsQueryModuleHandle *somTD_M_WPSamF_clsQueryModuleHandle;
#define somMD_M_WPSamF_clsQueryModuleHandle "----"
#define M_WPSamF_clsQueryModuleHandle(somSelf) \
    (SOM_Resolve(somSelf, M_WPSamF, clsQueryModuleHandle) \
	(somSelf))
#define _clsQueryModuleHandle M_WPSamF_clsQueryModuleHandle

/*
 * New Method: clsIsShareware
 */
typedef BOOL    SOMLINK somTP_M_WPSamF_clsIsShareware(M_WPSamF *somSelf);
#pragma linkage(somTP_M_WPSamF_clsIsShareware, system)
typedef somTP_M_WPSamF_clsIsShareware *somTD_M_WPSamF_clsIsShareware;
#define somMD_M_WPSamF_clsIsShareware "----"
#define M_WPSamF_clsIsShareware(somSelf) \
    (SOM_Resolve(somSelf, M_WPSamF, clsIsShareware) \
	(somSelf))
#define _clsIsShareware M_WPSamF_clsIsShareware

/*
 * New Method: clsAbout
 */
typedef void    SOMLINK somTP_M_WPSamF_clsAbout(M_WPSamF *somSelf);
#pragma linkage(somTP_M_WPSamF_clsAbout, system)
typedef somTP_M_WPSamF_clsAbout *somTD_M_WPSamF_clsAbout;
#define somMD_M_WPSamF_clsAbout "----"
#define M_WPSamF_clsAbout(somSelf) \
    (SOM_Resolve(somSelf, M_WPSamF, clsAbout) \
	(somSelf))
#define _clsAbout M_WPSamF_clsAbout

/*
 * Declare the class creation procedure
 */
SOMEXTERN SOMAny * SOMLINK M_WPSamFNewClass(integer4 scemajorVersion,
		integer4 sceminorVersion);
#pragma linkage(M_WPSamFNewClass, system)

/*
 * Declare the class data structure
 */
SOMEXTERN struct M_WPSamFClassDataStructure {
	SOMAny *classObject;
	somMToken clsQueryModuleHandle;
	somMToken clsIsShareware;
	somMToken clsAbout;
} M_WPSamFClassData;

/*
 * Declare the C specific class data structure
 */
SOMEXTERN struct M_WPSamFCClassDataStructure {
	somMethodTab *parentMtab;
	somDToken instanceDataToken;
} M_WPSamFCClassData;

#endif       /* WPSAMF_h */
